[services]

[services.server]
HOST = "80.87.197.206"
PORT = ":4000"
LOG_LEVEL = "error"
TMP = "/var/www/html/tmp"

[services.database]
DB_URL = "postgres://exchanger:oHEKX73YQsZMSZo05@localhost:5432/exchanger_prod?sslmode=disable"

[services.redis]
HOST = "localhost"
PORT = 6379
DB = 1

[services.nsq]
HOST = "80.87.197.206"
PORT = 4150


[secrets]
ACCESS_SECRET = "uhOmoMnMvOyfHizBVB7DlA0TcyHF3ySfg1tfi1Ay"
REFRESH_SECRET = "5rfzJsTCTWkLdxb3iDmb0qKOI56n61aakB4y7KC9"
TOKEN_SECRET = "mxJ4sOO4JYIyWGvCSlno9KUf3oaF15LOgktDkM2s"


[users]
MANAGERS = []
DEVELOPERS = ["I0HuKc", "enthusedfir", "bau00"]
ADMINS = []


[plugins]

[plugins.whitebit]
PUBLIC_KEY = ""
PRIVATE_KEY = ""
URL = "https://whitebit.com"