[services]

[services.server]
HOST = "127.0.0.1"
PORT = ":4000"
LOG_LEVEL = "error"
TMP = "./tmp"

[services.database]
DB_URL = "postgres://exchanger:qwerty@localhost:5432/exchanger_server_dev?sslmode=disable"

[services.redis]
HOST = "localhost"
PORT = 6379
DB = 1

[services.nsq]
HOST = "80.87.197.206"
PORT = 4150


[secrets]
ACCESS_SECRET = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
REFRESH_SECRET = "JzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikpva"
TOKEN_SECRET = "SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"


[users]
MANAGERS = []
DEVELOPERS = ["I0HuKc", "enthusedfir"]
ADMINS = []


[plugins]
AES_KEY = "fn5LyPGTnB18gl24nieHavsmKfKRmvLR"